### ISSUE TITLE
FatalErrorException in DatatableListener

### ISSUE THREAD

**Issue by webkod3r** [AliHichem/AliDatatableBundle#127]
Hi @AliHichem I need your help as soon as possible, please.
I'm using the last version of symfony 2.3 branch and `"ali/datatable": "dev-master"`. Just including this line in **AppKernel.php**:

`new Ali\DatatableBundle\AliDatatableBundle(),`

and this one in **config.yml**

```
ali_datatable:
    all:
        action: true
        search: false
    js:
        iDisplayLength: "10"
        aLengthMenu: "[[5,10, 25, 50, -1], [5,10, 25, 50, 'Todo']]"
```

I got this error:

`FatalErrorException: Error: Call to undefined method Symfony\Component\HttpKernel\Event\FilterResponseEvent::isMasterRequest() in D:\Work\Projects\Acme\vendor\ali\datatable\Ali\DatatableBundle\EventListener\DatatableListener.php line 42`

This tag `dev-master` include the version 2.0 for this bundle? You've seen this error before? Have you any idea how to fix this?

Thanks in advance
WK
