### ISSUE TITLE
special characters encoding in string with variable (fr translation)

### ISSUE THREAD

**Issue by tontione** [AliHichem/AliDatatableBundle#159]
I use the message.fr.yml for french translation , but there is a bad display for string sInfo.
sInfo: "Affichage de l'élément _START_ à _END_ sur _TOTAL_ éléments"
the "à" character is not correctly displayed : little square on IE, black losange with ? in ff.
Other "é" special character is correctly displayed.

I tested by adding it to sPrevious string : "Précédent" => "Précédent à" , and there it is correctly displayed ! 
So i think it's perhaps because sInfo is a string with integrated variables ( _START_ and  _TOTAL_ ) !?

Any idea how to resolve this ?

**Comment by AliHichem** [comment]
I'm not reproducing this issue with the french translation with FF and Chrome and I didn't check with IE yet but as you're having this problem even with FF I guess it's about an encoding issue on your end.

**Comment by maxpou** [comment]
Hi, 
Tontione is a co-worker.

According to the [translation documentation](https://github.com/AliHichem/AliDatatableBundle/blob/master/Resources/doc/index.md#-translation), I have created a translation file.

Everything works except sInfo :

```yml
#app\Resources\translation\messages.fr.yml
ali:
    common:
        action: Actions
        #...
        sInfo: "Affichage des éléments _START_ à _END_ sur _TOTAL_ éléments"
        #...
```
(I have a special character between **_START_** and **_END_**).
Note that special characters works everywhere, except between this two keywords.

This is the output :
![special character problem](http://img15.hostingpics.net/pics/886919Capture.png)

Regards,
Maxpou
