### ISSUE TITLE
Notice: Undefined index: nommarque

### ISSUE THREAD

**Issue by lammh** [AliHichem/AliDatatableBundle#84]
Hello  thank you for your bundle, it is very useful for me. 
I probleme with a join between the tables. 
the model table contains foreign category key table and mark 
Here the entity: Model: 

```
Centre\FormationBundle\Entity\Modele:
    type: entity
    table: modele
    indexes:
        idmarque:
            columns:
                - idmarque
        idcategorie:
            columns:
                - idcategorie
    id:
        idmodele:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomModele:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            column: nom_modele
        bagage:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        nbporte:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        carburation:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        equipement:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
        image:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
    manyToOne:
        idmarque:
            targetEntity: Marque
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idmarque:
                    referencedColumnName: idmarque
            orphanRemoval: false
        idcategorie:
            targetEntity: Categorie
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcategorie:
                    referencedColumnName: idcategorie
            orphanRemoval: false
    lifecycleCallbacks: {  }
```

here is my controller: 

```
private function _datatable()
{

    return $this->get('datatable')
        ->setEntity("CentreFormationBundle:Modele", "e")                          // replace "XXXMyBundle:Entity" by your entity
        ->setFields(
            array(
                "Nom Modele"          => 'e.nomModele',
                "Nombre  Bagage"          => 'e.bagage',
                "Nombre Porte"          => 'e.nbporte',// Declaration for fields:
                "Carburation"          => 'e.carburation',
                "Equipement"          => 'e.equipement',
                "Image"          => 'e.image',//      "label" => "alias.field_attribute_for_dql"
                "Marque"         => 'm.nommarque',

                "_identifier_"  => 'e.idmodele')                          // you have to put the identifier field without label. Do not replace the "_identifier_"
        )
        ->addJoin('e.idmarque', 'm', \Doctrine\ORM\Query\Expr\Join::INNER_JOIN)


        ->setOrder("e.idmodele", "desc")                                 // it's also possible to set the default order
        ->setHasAction(true);



                                           // you can disable action column from here by setting "false".
}
```

when I execute the following I errors: 

```
Notice: Undefined index: nommarque in C:\wamp\www\Formations\vendor\ali\datatable\Ali\DatatableBundle\Util\Factory\Query\DoctrineBuilder.php line 217

in C:\wamp\www\Formations\vendor\ali\datatable\Ali\DatatableBundle\Util\Factory\Query\DoctrineBuilder.php at line 217   -
            $map = $this->_toArray($object); 
            foreach ($selectFields as $key) 
            { 
                $d[] = $map[$key]; 
            } 
            $data[] = $d; 
        } 
at ErrorHandler ->handle ('8', 'Undefined index: nommarque', 'C:\wamp\www\Formations\vendor\ali\datatable\Ali\DatatableBundle\Util\Factory\Query\DoctrineBuilder.php', '217', array('hydration_mode' => '2', 'request' => object(Request), 'dql_fields' => array('e.nomModele', 'e.bagage', 'e.nbporte', 'e.carburation', 'e.equipement', 'e.image', 'm.nommarque', 'e.idmodele'), 'order_field' => null, 'qb' => object(QueryBuilder), 'query' => object(Query), 'iDisplayLength' => '0', 'objects' => array(object(Modele), object(Modele), object(Modele), object(Modele), object(Modele), object(Modele), object(Modele), object(Modele), object(Modele), object(Modele), object(Modele), object(Modele), object(Modele)), 'selectFields' => array('nomModele', 'bagage', 'nbporte', 'carburation', 'equipement', 'image', 'nommarque', 'idmodele'), 'label' => '_identifier_', 'selector' => 'e.idmodele', 'has_alias' => '0', 'matches' => array(array(), array()), '_f' => 'e.idmodele', 'data' => array(), 'object' => object(Modele), 'd' => array('Symbol', '4', '5', 'essence', '5 chevaux manuelles essence, fermeture centrale, vitres avant électriques, 5 portes, 5 places, climatisation, Airbag, poste CD lecteur MP3.', 'renault_symbole1.jpg'), 'map' => array('filenameForRemove' => null, 'file' => null, 'nomModele' => 'Symbol', 'bagage' => '4', 'nbporte' => '5', 'carburation' => 'essence', 'equipement' => '5 chevaux manuelles essence, fermeture centrale, vitres avant électriques, 5 portes, 5 places, climatisation, Airbag, poste CD lecteur MP3.', 'image' => 'renault_symbole1.jpg', 'idmodele' => '1', 'idcategorie' => object(Categorie), 'idmarque' => object(Marque)), 'key' => 'nommarque')) 
in C:\wamp\www\Formations\vendor\ali\datatable\Ali\DatatableBundle\Util\Factory\Query\DoctrineBuilder.php at line 217   + 
at DoctrineBuilder ->getData ('2') 
in C:\wamp\www\Formations\vendor\ali\datatable\Ali\DatatableBundle\Util\Datatable.php at line 129   + 
at Datatable ->execute () 
in C:\wamp\www\Formations\src\Centre\FormationBundle\Controller\modeleController.php at line 59   + 
at modeleController ->gridAction () 
at call_user_func_array (array(object(modeleController), 'gridAction'), array()) 
in C:\wamp\www\Formations\app\bootstrap.php.cache at line 1002   + 
at HttpKernel ->handleRaw (object(Request), '1') 
in C:\wamp\www\Formations\app\bootstrap.php.cache at line 976   + 
at HttpKernel ->handle (object(Request), '1', true) 
in C:\wamp\www\Formations\app\bootstrap.php.cache at line 1101   + 
at ContainerAwareHttpKernel ->handle (object(Request), '1', true) 
in C:\wamp\www\Formations\app\bootstrap.php.cache at line 411   + 
at Kernel ->handle (object(Request)) 
in C:\wamp\www\Formations\web\app_dev.php at line 26   + 
```

thank you for your help
